// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Loaddr Ltd

// Setup script for the email module.
// Detects provider from email address, prompts for app password, generates himalaya config.
// Invoked via: npx tsx ./setup.ts (from authCommand in module.json)

import { execFileSync } from 'child_process';
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { createInterface } from 'readline';
import os from 'os';

const CONFIG_DIR = join(os.homedir(), '.config', 'himalaya');
const CONFIG_PATH = join(CONFIG_DIR, 'config.toml');
const KEYCHAIN_SERVICE = 'opentidy-email';

interface ProviderConfig {
  name: string;
  imapHost: string;
  imapPort: number;
  smtpHost: string;
  smtpPort: number;
  appPasswordUrl: string;
  folderAliases?: Record<string, string>;
}

const PROVIDERS: Record<string, ProviderConfig> = {
  'gmail.com': {
    name: 'Gmail',
    imapHost: 'imap.gmail.com', imapPort: 993,
    smtpHost: 'smtp.gmail.com', smtpPort: 587,
    appPasswordUrl: 'https://myaccount.google.com/apppasswords',
    folderAliases: { sent: '[Gmail]/Sent Mail', drafts: '[Gmail]/Drafts', trash: '[Gmail]/Trash' },
  },
  'googlemail.com': {
    name: 'Gmail',
    imapHost: 'imap.gmail.com', imapPort: 993,
    smtpHost: 'smtp.gmail.com', smtpPort: 587,
    appPasswordUrl: 'https://myaccount.google.com/apppasswords',
    folderAliases: { sent: '[Gmail]/Sent Mail', drafts: '[Gmail]/Drafts', trash: '[Gmail]/Trash' },
  },
  'outlook.com': {
    name: 'Outlook',
    imapHost: 'outlook.office365.com', imapPort: 993,
    smtpHost: 'smtp-mail.outlook.com', smtpPort: 587,
    appPasswordUrl: 'https://account.live.com/proofs/AppPassword',
  },
  'hotmail.com': {
    name: 'Outlook',
    imapHost: 'outlook.office365.com', imapPort: 993,
    smtpHost: 'smtp-mail.outlook.com', smtpPort: 587,
    appPasswordUrl: 'https://account.live.com/proofs/AppPassword',
  },
  'live.com': {
    name: 'Outlook',
    imapHost: 'outlook.office365.com', imapPort: 993,
    smtpHost: 'smtp-mail.outlook.com', smtpPort: 587,
    appPasswordUrl: 'https://account.live.com/proofs/AppPassword',
  },
  'yahoo.com': {
    name: 'Yahoo',
    imapHost: 'imap.mail.yahoo.com', imapPort: 993,
    smtpHost: 'smtp.mail.yahoo.com', smtpPort: 587,
    appPasswordUrl: 'https://login.yahoo.com/account/security/app-passwords',
  },
  'icloud.com': {
    name: 'iCloud',
    imapHost: 'imap.mail.me.com', imapPort: 993,
    smtpHost: 'smtp.mail.me.com', smtpPort: 587,
    appPasswordUrl: 'https://appleid.apple.com/account/manage',
  },
  'me.com': {
    name: 'iCloud',
    imapHost: 'imap.mail.me.com', imapPort: 993,
    smtpHost: 'smtp.mail.me.com', smtpPort: 587,
    appPasswordUrl: 'https://appleid.apple.com/account/manage',
  },
  'fastmail.com': {
    name: 'Fastmail',
    imapHost: 'imap.fastmail.com', imapPort: 993,
    smtpHost: 'smtp.fastmail.com', smtpPort: 587,
    appPasswordUrl: 'https://www.fastmail.com/settings/security/devicekeys',
  },
  'protonmail.com': {
    name: 'ProtonMail (via Bridge)',
    imapHost: '127.0.0.1', imapPort: 1143,
    smtpHost: '127.0.0.1', smtpPort: 1025,
    appPasswordUrl: 'https://proton.me/support/protonmail-bridge-configure-client',
  },
  'proton.me': {
    name: 'ProtonMail (via Bridge)',
    imapHost: '127.0.0.1', imapPort: 1143,
    smtpHost: '127.0.0.1', smtpPort: 1025,
    appPasswordUrl: 'https://proton.me/support/protonmail-bridge-configure-client',
  },
};

// Single shared readline interface (creating multiple causes stdin issues in tmux/ttyd)
const rl = createInterface({ input: process.stdin, output: process.stderr });

function prompt(question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

function storeInKeychain(account: string, key: string, password: string): void {
  const service = `${KEYCHAIN_SERVICE}-${key}`;
  // Delete existing entry if any
  try { execFileSync('security', ['delete-generic-password', '-s', service, '-a', account], { stdio: 'pipe' }); } catch { /* ignore */ }
  execFileSync('security', ['add-generic-password', '-s', service, '-a', account, '-w', password], { stdio: 'pipe' });
}

function generateConfig(email: string, provider: ProviderConfig | null, imapHost: string, smtpHost: string, imapPort: number, smtpPort: number): string {
  const accountName = 'default';
  const folderAliases = provider?.folderAliases ?? {};

  let config = `# Generated by OpenTidy email module setup
[accounts.${accountName}]
default = true
email = "${email}"
`;

  // Folder aliases
  config += `folder.aliases.inbox = "INBOX"\n`;
  if (folderAliases.sent) config += `folder.aliases.sent = "${folderAliases.sent}"\n`;
  if (folderAliases.drafts) config += `folder.aliases.drafts = "${folderAliases.drafts}"\n`;
  if (folderAliases.trash) config += `folder.aliases.trash = "${folderAliases.trash}"\n`;

  // IMAP
  const isProton = imapHost === '127.0.0.1';
  config += `
backend.type = "imap"
backend.host = "${imapHost}"
backend.port = ${imapPort}
backend.encryption.type = "${isProton ? 'none' : 'tls'}"
backend.login = "${email}"
backend.auth.type = "password"
backend.auth.cmd = "security find-generic-password -s ${KEYCHAIN_SERVICE}-imap -a ${email} -w"
`;

  // SMTP
  config += `
message.send.backend.type = "smtp"
message.send.backend.host = "${smtpHost}"
message.send.backend.port = ${smtpPort}
message.send.backend.encryption.type = "${isProton ? 'none' : 'start-tls'}"
message.send.backend.login = "${email}"
message.send.backend.auth.type = "password"
message.send.backend.auth.cmd = "security find-generic-password -s ${KEYCHAIN_SERVICE}-smtp -a ${email} -w"

message.send.save-copy = true
message.delete.style = "folder"
`;

  return config;
}

async function main(): Promise<void> {
  console.log('\n📧 Email Setup\n');

  // Step 1: Check himalaya
  // tmux sessions may not have Homebrew in PATH; check common locations
  const brewPaths = ['/opt/homebrew/bin', '/usr/local/bin'];
  const envPath = [process.env.PATH, ...brewPaths].filter(Boolean).join(':');
  const execOpts = { encoding: 'utf-8' as const, env: { ...process.env, PATH: envPath } };

  let himalayaBin = 'himalaya';
  const parseVersion = (raw: string) => raw.match(/himalaya v[\d.]+/)?.[0] ?? raw.split('\n')[0];
  try {
    const version = execFileSync('himalaya', ['--version'], execOpts).trim();
    console.log(`✓ ${parseVersion(version)}\n`);
  } catch {
    // Try finding it in brew paths directly
    const found = brewPaths.map(p => join(p, 'himalaya')).find(p => existsSync(p));
    if (found) {
      himalayaBin = found;
      const version = execFileSync(found, ['--version'], execOpts).trim();
      console.log(`✓ ${parseVersion(version)}\n`);
    } else {
      console.log('himalaya not found. Installing via Homebrew...\n');
      const brewBin = brewPaths.map(p => join(p, 'brew')).find(p => existsSync(p)) ?? 'brew';
      try {
        execFileSync(brewBin, ['install', 'himalaya'], { stdio: 'inherit', timeout: 120_000, env: { ...process.env, PATH: envPath } });
        himalayaBin = brewPaths.map(p => join(p, 'himalaya')).find(p => existsSync(p)) ?? 'himalaya';
        console.log('');
      } catch {
        console.error('❌ Failed to install himalaya. Install manually: brew install himalaya');
        process.exit(1);
      }
    }
  }

  // Step 2: Email address
  const email = await prompt('Email address: ');
  if (!email || !email.includes('@')) {
    console.error('❌ Invalid email address');
    process.exit(1);
  }

  const domain = email.split('@')[1].toLowerCase();
  const provider = PROVIDERS[domain] ?? null;

  if (provider) {
    console.log(`\n✓ ${provider.name} detected\n`);
  } else {
    console.log(`\nCustom provider (${domain})\n`);
  }

  // Step 3: IMAP/SMTP settings (auto-detect or ask)
  let imapHost: string, smtpHost: string, imapPort: number, smtpPort: number;

  if (provider) {
    imapHost = provider.imapHost;
    smtpHost = provider.smtpHost;
    imapPort = provider.imapPort;
    smtpPort = provider.smtpPort;
  } else {
    imapHost = await prompt('IMAP host: ');
    const imapPortStr = await prompt('IMAP port (993): ');
    imapPort = imapPortStr ? parseInt(imapPortStr, 10) : 993;
    smtpHost = await prompt('SMTP host: ');
    const smtpPortStr = await prompt('SMTP port (587): ');
    smtpPort = smtpPortStr ? parseInt(smtpPortStr, 10) : 587;
  }

  // Step 4: App Password
  if (provider?.appPasswordUrl) {
    console.log(`Create an App Password for OpenTidy:`);
    console.log(`→ ${provider.appPasswordUrl}\n`);
  }

  const rawPassword = await prompt('App Password (or email password): ');
  if (!rawPassword) {
    console.error('❌ No password entered');
    process.exit(1);
  }
  // Gmail app passwords are displayed with spaces (e.g. "dfwj vokc jarq mcuv"), strip them
  const appPassword = rawPassword.replace(/\s+/g, '');

  // Step 5: Store password in macOS Keychain
  try {
    storeInKeychain(email, 'imap', appPassword);
    storeInKeychain(email, 'smtp', appPassword);
    console.log('✓ Password stored in OS keychain\n');
  } catch (err) {
    console.error('❌ Failed to store password in keychain:', (err as Error).message);
    process.exit(1);
  }

  // Step 6: Generate config
  mkdirSync(CONFIG_DIR, { recursive: true });

  if (existsSync(CONFIG_PATH)) {
    const existing = readFileSync(CONFIG_PATH, 'utf-8');
    const backup = `${CONFIG_PATH}.backup.${Date.now()}`;
    writeFileSync(backup, existing);
    console.log(`⚠ Existing config backed up to ${backup}`);
  }

  const config = generateConfig(email, provider, imapHost, smtpHost, imapPort, smtpPort);
  writeFileSync(CONFIG_PATH, config);
  console.log(`✓ Config written to ${CONFIG_PATH}\n`);

  // Step 7: Test connection
  console.log('Testing connection...\n');
  try {
    const result = execFileSync(himalayaBin, ['envelope', 'list', '--page-size', '1'], {
      encoding: 'utf-8',
      timeout: 30_000,
      env: { ...process.env, PATH: envPath },
    });
    console.log(result.trim());
    console.log('\n✅ Email setup complete!\n');
  } catch (err) {
    const stderr = (err as any).stderr?.toString() || (err as Error).message;
    console.error('❌ Connection test failed:', stderr.slice(0, 300));
    console.error('\nCheck your email/password and try again. For Gmail, make sure 2FA is enabled and you\'re using an App Password.');
    process.exit(1);
  }
}

main().catch((err) => {
  console.error('❌ Setup failed:', (err as Error).message);
  process.exit(1);
}).finally(() => rl.close());
